# Test playbook
---
- hosts: all
  become: true
  vars:
    NS: TRAVIS
    openio_bootstrap: true
  roles:
    - role: repository
      openio_repository_no_log: false
      openio_repository_mirror_host: mirror2.openio.io
    - role: users
    - role: gridinit
      openio_gridinit_namespace: "{{ NS }}"
      #openio_gridinit_per_ns: true
    - role: namespace
      openio_namespace_name: "{{ NS }}"
    - role: conscience
      openio_conscience_namespace: "{{ NS }}"
      openio_conscience_bind_address: "{{ ansible_default_ipv4.address }}"
      openio_conscience_pools: []
      openio_conscience_inventory_groupname: all
      openio_conscience_multiple: false
    - role: meta
      openio_meta_namespace: "{{ NS }}"
    - role: oioproxy
      openio_oioproxy_namespace: "{{ NS }}"
    - role: role_under_test
      openio_conscienceagent_namespace: "{{ NS }}"
...
